FROM golang:1.21.3-bookworm as build

WORKDIR /app

COPY go.mod go.sum main.go /app/

RUN go build -o vulnerable-awk-playground ./main.go

FROM ubuntu:23.10

COPY --from=build /app/vulnerable-awk-playground /usr/bin/

ENTRYPOINT ["vulnerable-awk-playground"]
