FROM golang:1.21.3-alpine3.18 as build

WORKDIR /app

COPY go.mod go.sum main.go /app/

RUN go build -o vulernable-awk-playground ./main.go

FROM cgr.dev/chainguard/busybox:latest

COPY --from=build /app/vulernable-awk-playground /usr/bin/

ENTRYPOINT ["vulernable-awk-playground"]
