# This is version 1  of the build via dockerfile. It is suboptimal, as it doesn't leverage
# multi-stage build, which means the resulting image will have the full golang toolchain installed

FROM golang:1.21.3-bookworm

WORKDIR /app

COPY go.mod go.sum main.go /app/

RUN go build -o vulernable-awk-playground ./main.go

RUN cp vulernable-awk-playground /usr/bin/

ENTRYPOINT ["vulernable-awk-playground"]
