FROM golang:1.21.3-alpine3.18 as build

WORKDIR /app

COPY go.mod go.sum main.go /app/

RUN go build -o vulnerable-awk-playground ./main.go

FROM alpine:3.18

COPY --from=build /app/vulnerable-awk-playground /usr/bin/

ENTRYPOINT ["vulnerable-awk-playground"]
